config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'devise_auth/registrations',
    sessions: 'devise_auth/sessions',
    passwords: 'devise_auth/passwords',
    confirmations: 'devise_auth/confirmations'
  }

  root 'dashboard#home'

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable

  validates :first_name, :last_name, presence: true, on: [:create]
  validate :password_verification, on: [:create]

  private

  def password_verification
    return if password.length >= 8 && password =~ /[0-9]/

    errors.add :password, 'must contain at least one digit and have at least 8 characters'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!, unless: :devise_controller?
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  skip_before_action :authenticate_user!

  def home

  end
end

app/controllers/devise_auth/confirmations_controller.rb
module DeviseAuth
  class ConfirmationsController < Devise::ConfirmationsController
    def create
      self.resource = resource_class.send_confirmation_instructions(resource_params)

      if successfully_sent?(resource)
        redirect_to new_user_session_path, notice: 'an email for account confirmation was sent to the address'
      else
        redirect_to new_user_confirmation_path, alert: resource.errors.full_messages
      end
    end
  end
end

app/controllers/devise_auth/passwords_controller.rb
module DeviseAuth
  class PasswordsController < Devise::PasswordsController
    def create
      self.resource = resource_class.send_reset_password_instructions(resource_params)

      if successfully_sent?(resource)
        redirect_to new_user_session_path, notice: 'an email for password reset was sent to the address'
      else
        redirect_to new_user_password_path, alert: resource.errors.full_messages
      end
    end

    def update
      self.resource = resource_class.reset_password_by_token(resource_params)

      if resource.errors.empty?
        redirect_to new_user_session_path, notice: 'password was successfully changed'
      else
        set_minimum_password_length
        redirect_to edit_user_password_path(reset_password_token: params[:user][:reset_password_token]), alert: resource.errors.full_messages
      end
    end
  end
end

app/controllers/devise_auth/registrations_controller.rb
module DeviseAuth
  class RegistrationsController < Devise::RegistrationsController
    def create
      build_resource(sign_up_params)

      resource.save
      if resource.persisted?
        expire_data_after_sign_in!
        redirect_to new_user_session_path, notice: 'an activation email was sent to your address'
      else
        clean_up_passwords resource
        set_minimum_password_length
        redirect_to new_user_registration_path, alert: resource.errors.full_messages
      end
    end

    def update
      self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)

      if resource_updated
        redirect_to_path
      else
        clean_up_passwords resource
        set_minimum_password_length
        redirect_to edit_user_registration_path, alert: resource.errors.full_messages
      end
    end

    private

    def without_password?
      params[:user][:current_password].nil?
    end

    def resource_updated
      if without_password?
        resource.update_without_password(account_update_params)
      else
        resource.update_with_password(account_update_params)
      end
    end

    def redirect_to_path
      if without_password?
        redirect_to edit_user_registration_path, notice: 'account info updated'
      else
        redirect_to new_user_session_path, notice: 'password changed. please log in again'
      end
    end
  end
end

app/controllers/devise_auth/sessions_controller.rb
module DeviseAuth
  class SessionsController < Devise::SessionsController
    def create
      catch(:warden) do
        super
        return
      end
      redirect_to new_user_session_path, alert: 'invalid email or password'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/home.html.erb
<div class="home-header">
  <div class="title">
    your tv show journal is here
  </div>
  <div class="subtitle">
    <p>always keep track of your favorite tv shows</p>
    <p>never forget where you left off a tv show</p>
  </div>
</div>

app/views/layouts/_flash_messages.html.erb
<div class="row">
  <% flash.each do |type, msg| %>
    <div class="alert flash-msg flash-<%= type %>">
      <% if msg.is_a? Array %>
        <% msg.each { |m| %><p><%= m.downcase %></p><%}
      else %>
        <%= msg.downcase %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-dark bg-dark" data-controller="navbar">
  <a class="navbar-brand" href="/">tvsJ</a>
  <div>
  <% if user_signed_in? %>
      <%= link_to 'tv shows', users_path, class: 'btn btn-outline-light btn-navbar', 'data-navbar-target': 'button',
                  'data-action':'mouseover->navbar#hover_button mouseout->navbar#unhover_button' %>
      <%= link_to 'journal', users_path, class: 'btn btn-outline-light btn-navbar', 'data-navbar-target': 'button',
                  'data-action':'mouseover->navbar#hover_button mouseout->navbar#unhover_button' %>
      <%= link_to 'account', edit_user_registration_path, class: 'btn btn-outline-light btn-navbar', 'data-navbar-target': 'button',
                  'data-action':'mouseover->navbar#hover_button mouseout->navbar#unhover_button' %>
      <%= link_to 'log out', destroy_user_session_path, method: :delete, class: 'btn btn-outline-light btn-navbar', 'data-navbar-target': 'button',
                  'data-action':'mouseover->navbar#hover_button mouseout->navbar#unhover_button' %>
  <% elsif !devise_controller? %>
      <%= link_to 'log in', new_user_session_path, class: 'btn btn-outline-light btn-navbar', 'data-navbar-target': 'button',
                  'data-action':'mouseover->navbar#hover_button mouseout->navbar#unhover_button' %>
  <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TvsJ</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
  <%= render 'layouts/flash_messages' %>
  <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<% @users.each { |user| %><p><%= user.email %></p><% } %>

app/views/users/show.html.erb
<%= current_user.email %>